# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Eliseo Papa
tagline:          'Thoughts, ideas and projects. Here so they can be safely ignored.'
description:      'Biomedical engineer, computational biologist, doctor'
baseurl:          "http://elipapa.github.io"
production_url:   'http://www.eliseopapa.org'

author:
  name:           'Eliseo Papa'
  url:            'http://www.eliseopapa.org'

paginate:         2
paginate_path:    "blog/page:num"

# Custom vars
repo:             "http://github.com/elipapa/elipapa.github.io"
