# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Eliseo Papa
tagline:          'Thoughts, ideas and projects. Here so they can be safely ignored.'
description:      'Biomedical engineer, computational biologist, doctor'
baseurl:           "http://elipapa.github.io"

author:
  name:           'Eliseo Papa'
  url:        'https://eliseopapa.org'

paginate:         5

# Custom vars
repo:           "https://github.com/elipapa/elipapa.github.io"
