# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /blog/:categories/:title.html

# Setup
title:            Eliseo Papa
tagline:          'Thoughts, ideas and projects. Here so they can be safely ignored.'
description:      'Biomedical engineer, computational biologist, doctor'
production_url:   'http://elipapa.github.io'

author:
  name:           'Eliseo Papa'
  url:            'http://elipapa.github.io'

paginate:         8
paginate_path:    "blog/:num"

# Custom vars
repo:             "http://github.com/elipapa/elipapa.github.io"

# let github generate a sitemap.xml for you
gems:
  - jekyll-sitemap
  - jekyll-paginate
